### ISSUE TITLE
branches config does not work at all

### ISSUE THREAD

**Issue by dogmatic69** [repository-settings/app#857] opened 2024-01-31 15:04 UTC
## Problem Description

Unable to define branch protection rules through the `branches` configuration. 

I've tried numerous iterations, including a direct copy/paste from the docs. No branch protection is ever created.

### What is actually happening

nothing at all.

### What is the expected behaviour

branch protection rules should be created / maintained by the app

### Error output, if available

```
n/a
```

### Are you using the hosted instance of repository-settings/app or running your own?

hosted

**Comment by venkatamutyala** [comment] 2024-04-08 23:20
I'm having the same problem. Assuming that it's a bug is there a way to debug/alert on when there are issues like this? I don't want to be in a situation where I think this is enabled on my repos and it turns out it's not.

**Comment by xCykrix** [comment] 2024-04-17 19:24
+1 as well. Even a previously known working configuration is no longer working.

**Comment by xCykrix** [comment] 2024-04-17 19:55
CC @travi

**Comment by travi** [comment] 2024-04-19 21:44
> is there a way to debug/alert on when there are issues like this?

that is the goal of https://github.com/repository-settings/app/issues/518, which has not been implemented yet

configuring branch protection with this app _does_ work as long as the protection details are configured correctly and no other failures occurred before the app attempts to update the branch protection config through the api. unfortunately, there is no feedback from the app about a failure until https://github.com/repository-settings/app/issues/518 is implemented, so the best i can offer until then is to suggest removing details from your config until it works and then add details back into your config detail by detail and confirming each applies successfully.

**Comment by travi** [comment] 2024-04-19 21:45
duplicate of https://github.com/repository-settings/app/issues/150. please avoid opening extra issues when relevant issues already exist

**Closed by travi** 2024-04-19 21:45 UTC
Labels: bug
